.TH script.tidy 1
.SH NAME
script.tidy \- remove extra carriage returns and backspaces
.SH SYNOPSIS
.B script.tidy
.SH DESCRIPTION
This filter
does a bit of postprocessing,
typically on a typescript produced by
.B script.
It removes extra carriage returns
and wipes out backspaced characters.
.SH "SEE ALSO"
script(1)
