WARNING: Do not change this file without changing Makefile accordingly!
#include "config/sessfile.h"
X!/bin/sh
X if you want to save SESSLOG_FILE.7, do it now!
mv SESSLOG_FILE.6 SESSLOG_FILE.7
mv SESSLOG_FILE.5 SESSLOG_FILE.6
mv SESSLOG_FILE.4 SESSLOG_FILE.5
mv SESSLOG_FILE.3 SESSLOG_FILE.4
mv SESSLOG_FILE.2 SESSLOG_FILE.3
mv SESSLOG_FILE.1 SESSLOG_FILE.2
mv SESSLOG_FILE.0 SESSLOG_FILE.1
ln SESSLOG_FILE SESSLOG_FILE.0
cp SESSLOG_FILE SESSLOG_FILE.new; : > SESSLOG_FILE.new
chmod 644 SESSLOG_FILE.new; mv SESSLOG_FILE.new SESSLOG_FILE
