.TH talkacros 7
.SH NAME
talkacros \- some acronyms commonly used in screen conversation
.SH DESCRIPTION
Many abbreviations are commonly used between people engaged in
low-delay typed conversations.
Here are a few of them:
.TP 5
jam
Just a minute.
.TP
\:-)
Smiley-face.
(Look at it sideways.)
This can mean anything
from a grin to a grimace,
depending on the context.
.TP
\:-(
Frown.
.TP
t
True (from LISP).
.TP
ayt
Are you there?
(An answer of no
means that the other person is
busy with something else.)
.TP
ga
Go ahead.
.TP
tyl
Talk to you later.
.TP
oo
Over and out.
.PP
.SH BUGS
The author's biases have almost completely determined
the selection of acronyms for this list.
.SH "SEE ALSO"
talk(1), write(1)
