.TH tplay 1
.SH NAME
tplay \- play back a tape-recorded input
.SH SYNTAX
.B tplay
.SH DESCRIPTION
.B tplay
replays a
.I tape
recorded by
.B trecord.
It pauses to produce the same timing as the original input to
.B trecord
(down to the resolution of the system clock).
.SH VERSION
tplay version 1.0, 7/27/91.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
trecord(1)
