.TH whoami 1
.SH NAME
whoami \- print effective username
.SH SYNTAX
whoami
.SH DESCRIPTION
.B whoami
prints the username
corresponding to the effective userid,
or the numeric userid if no username is available.
.SH COMPATIBILITY
.B whoami
originated with BSD systems and typically is not available
under System V.
However, this is a straight clone.
.SH VERSION
whoami version 1.0, 7/22/91.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
getuid(2)
